ktor:
  application:
    modules:
      - ch.michu.tech.tui.backend.ApplicationKt.setupTuiBackend
      - ch.michu.tech.tui.demo.backend.ApplicationKt.setupTodo
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/tui_demo"
  user: postgres
  password: postgres